title: Duong T Phan
description: Mechanical Engineer
site_title: '@shadowoxe - DuongTPhanPortfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ShadowOxe
#blog_url: 
email: duong344332@gmail.com
#keybase_username: 
#twitter_username: 
#reddit_username: 

# absolute or relative
profile_picture: assets/images/ProfilePicture.png

# Google Analytics ID
google_analytics: G-Z217ZRRYHY
